"""
PhysiCell snapshot reader and spatial statistics computation.

This module parses PhysiCell agent-based model output (CSV snapshots and
``.mat`` snapshots) and recomputes the same node/edge/neighbor schema
used internally by ``GraphColorizer`` (``node_counts``, ``edge_counts``,
``neighbor_dist``). It is intended for comparing ABM-evolved tissue states
against initial-condition targets generated by this package.

The :func:`stats_to_target_statistics` adapter converts the output of
:meth:`PhysiCellReader.compute_spatial_stats` into the
:class:`~tissue_simulator.replicate_generator.TargetStatistics` dataclass
expected by :class:`~tissue_simulator.replicate_generator.ReplicateGenerator`.

CREDITS
-------
The PhysiCell ``.mat`` snapshot layout and the cell-definition XML schema
used by :meth:`PhysiCellReader.load_snapshot_mat` are documented and
reference-implemented by the PhysiCell-Tools ``python-loader`` project
(``pyMCDS`` / ``pcdl``), distributed under the BSD-3-Clause license:

    https://github.com/PhysiCell-Tools/python-loader

When the optional ``pyMCDS`` / ``pcdl`` package is installed, the reader
delegates to it for full-fidelity parsing. Otherwise it falls back to a
direct ``scipy.io.loadmat`` parser based on the documented PhysiCell 1.10+
default cells-matrix column layout (see ``load_snapshot_mat``). Neither
``pyMCDS`` nor ``pcdl`` is a required dependency of ``tissue_simulator``;
both are optional and only used when present.
"""

import csv
import glob
import os
import re
from collections import defaultdict
from typing import Dict, List, Optional, Tuple, Union

import numpy as np

try:
    from scipy.spatial import KDTree
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False


# Canonical numeric column aliases tolerated in PhysiCell CSV exports.
_NUMERIC_ALIASES = {
    "x": ("x", "position_x", "pos_x"),
    "y": ("y", "position_y", "pos_y"),
    "z": ("z", "position_z", "pos_z"),
    "radius": ("radius", "cell_radius", "r"),
    "volume": ("volume", "total_volume", "cell_volume"),
    "timestep": ("timestep", "time", "t", "step"),
    "id": ("id", "ID", "cell_id", "agent_id"),
}

_DEFAULT_RADIUS = 8.412710547954228  # PhysiCell default ~ (3/4 pi * 2494)^(1/3)


def _coerce_float(value: str) -> Optional[float]:
    """Convert a CSV string to float, returning None when not numeric."""
    if value is None:
        return None
    value = value.strip()
    if value == "" or value.lower() in {"nan", "none", "null"}:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _resolve_column(header: List[str], aliases: Tuple[str, ...]) -> Optional[str]:
    """Find the first header column matching any alias (case-insensitive)."""
    lower_map = {h.lower(): h for h in header}
    for alias in aliases:
        if alias.lower() in lower_map:
            return lower_map[alias.lower()]
    return None


def _volume_to_radius(volume: float) -> float:
    """Convert a spherical cell volume to a radius."""
    if volume is None or volume <= 0:
        return _DEFAULT_RADIUS
    return float((3.0 * volume / (4.0 * np.pi)) ** (1.0 / 3.0))


def _extract_timestep(filename: str) -> float:
    """Parse a numeric timestep token from a snapshot filename."""
    base = os.path.basename(filename)
    matches = re.findall(r"\d+(?:\.\d+)?", base)
    if not matches:
        return 0.0
    return float(matches[-1])


class PhysiCellReader:
    """
    Reader for PhysiCell snapshot output.

    Parses CSV and (optionally) ``.mat`` snapshots emitted by PhysiCell and
    recomputes the spatial statistics consumed by ``tissue_simulator``
    (``node_counts``, ``edge_counts``, ``neighbor_dist``).
    """

    def __init__(self, default_radius: float = _DEFAULT_RADIUS):
        """
        Initialize the reader.

        Parameters
        ----------
        default_radius : float
            Radius to assign when neither ``radius`` nor ``volume`` is
            present in the snapshot. Defaults to a PhysiCell-like value
            (~8.41 micrometers, the radius of a 2494 cubic micrometer cell).
        """
        self.default_radius = float(default_radius)

    # ------------------------------------------------------------------
    # Snapshot loaders
    # ------------------------------------------------------------------
    def load_snapshot_csv(self, csv_path: str) -> List[Dict]:
        """
        Load a PhysiCell CSV snapshot.

        Parameters
        ----------
        csv_path : str
            Path to a CSV file with at least the columns ``x``, ``y``, ``z``,
            and ``cell_type``. Optional columns: ``radius`` or ``volume``,
            ``timestep``, ``ID``.

        Returns
        -------
        list of dict
            One dict per cell with keys ``x``, ``y``, ``z``, ``radius``,
            ``cell_type``, and optionally ``timestep``, ``id``, ``volume``.
        """
        if not os.path.isfile(csv_path):
            raise FileNotFoundError(f"Snapshot CSV not found: {csv_path}")

        cells: List[Dict] = []
        with open(csv_path, "r", newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                return cells

            header = list(reader.fieldnames)
            col_x = _resolve_column(header, _NUMERIC_ALIASES["x"])
            col_y = _resolve_column(header, _NUMERIC_ALIASES["y"])
            col_z = _resolve_column(header, _NUMERIC_ALIASES["z"])
            col_radius = _resolve_column(header, _NUMERIC_ALIASES["radius"])
            col_volume = _resolve_column(header, _NUMERIC_ALIASES["volume"])
            col_timestep = _resolve_column(header, _NUMERIC_ALIASES["timestep"])
            col_id = _resolve_column(header, _NUMERIC_ALIASES["id"])
            col_type = _resolve_column(header, ("cell_type", "type", "celltype"))

            if col_x is None or col_y is None or col_type is None:
                raise ValueError(
                    "PhysiCell CSV must contain at minimum x, y, and "
                    f"cell_type columns. Got: {header}"
                )

            for row in reader:
                x = _coerce_float(row.get(col_x))
                y = _coerce_float(row.get(col_y))
                z = _coerce_float(row.get(col_z)) if col_z else 0.0
                if x is None or y is None:
                    continue
                if z is None:
                    z = 0.0

                radius = None
                if col_radius is not None:
                    radius = _coerce_float(row.get(col_radius))
                volume = None
                if col_volume is not None:
                    volume = _coerce_float(row.get(col_volume))
                if radius is None and volume is not None:
                    radius = _volume_to_radius(volume)
                if radius is None or radius <= 0:
                    radius = self.default_radius

                cell_type = (row.get(col_type) or "").strip()
                if not cell_type:
                    cell_type = "unknown"

                cell: Dict = {
                    "x": float(x),
                    "y": float(y),
                    "z": float(z),
                    "radius": float(radius),
                    "cell_type": cell_type,
                }
                if col_volume is not None and volume is not None:
                    cell["volume"] = float(volume)
                if col_timestep is not None:
                    ts = _coerce_float(row.get(col_timestep))
                    if ts is not None:
                        cell["timestep"] = float(ts)
                if col_id is not None:
                    raw_id = row.get(col_id)
                    if raw_id is not None and str(raw_id).strip() != "":
                        cell["id"] = str(raw_id).strip()

                cells.append(cell)

        return cells

    def load_snapshot_mat(self,
                          mat_path: str,
                          xml_path: Optional[str] = None) -> List[Dict]:
        """
        Load a PhysiCell ``.mat`` snapshot.

        Two backends are attempted, in order:

        1. **pyMCDS / pcdl** (optional dependency). If either of these
           packages is importable, the reader delegates to it for
           full-fidelity parsing. ``pyMCDS(xml_basename, output_path)``
           is preferred because the matching ``output*.xml`` is required
           to recover the cell-type name mapping. When only ``mat_path``
           is provided, this step is skipped (pyMCDS requires the XML).
        2. **Direct ``scipy.io.loadmat`` fallback** following the
           documented PhysiCell 1.10+ default cells-matrix layout:

           ===  ===================
           col  meaning
           ===  ===================
           0    ID
           1    position x
           2    position y
           3    position z
           4    total volume
           5    cell type (integer)
           ===  ===================

           The matrix is conventionally stored as
           ``(n_signals, n_cells)``, so axis 0 is the signals axis by
           default. We only treat axis 1 as the signals axis when axis 0
           is shorter than the six documented signals and axis 1 is long
           enough to hold them (i.e. the file was saved transposed). If
           neither axis can hold the standard six signals a
           ``ValueError`` is raised.

        Parameters
        ----------
        mat_path : str
            Path to a PhysiCell ``output*_cells.mat`` (or similar) file.
        xml_path : str, optional
            Path to the matching ``output*.xml``. When provided, the XML
            is parsed for ``<cell_definitions>`` to map integer cell-type
            IDs to human-readable names. Without it, cell types are
            stringified integer IDs (e.g. ``"0"``, ``"1"``) and a warning
            is emitted via :mod:`warnings`.

        Returns
        -------
        list of dict
            Cell records in the same schema as :meth:`load_snapshot_csv`:
            keys ``x``, ``y``, ``z``, ``radius``, ``cell_type``, and
            optionally ``volume``, ``id``.

        Raises
        ------
        FileNotFoundError
            If ``mat_path`` does not exist.
        ValueError
            If the file cannot be parsed as a MATLAB file, no cells
            matrix can be located, or its shape is incompatible with the
            documented PhysiCell layout.

        Notes
        -----
        The ``pyMCDS`` / ``pcdl`` package (BSD-3-Clause,
        https://github.com/PhysiCell-Tools/python-loader) is an optional
        dependency that provides reference-implementation parsing and is
        preferred when available. The direct fallback implements only
        the documented PhysiCell 1.10+ default layout and may not
        correctly decode custom-built PhysiCell binaries that emit a
        non-default signal ordering.
        """
        if not os.path.isfile(mat_path):
            raise FileNotFoundError(f"PhysiCell .mat snapshot not found: {mat_path}")

        # 1. Try pyMCDS / pcdl first (requires xml_path because pyMCDS
        # discovers the .mat through the .xml that lives beside it).
        if xml_path is not None and os.path.isfile(xml_path):
            cells = self._try_load_mat_with_pymcds(mat_path, xml_path)
            if cells is not None:
                return cells

        # 2. Direct scipy.io.loadmat fallback.
        return self._load_mat_with_scipy(mat_path, xml_path)

    # ------------------------------------------------------------------
    # .mat parsing helpers
    # ------------------------------------------------------------------
    def _try_load_mat_with_pymcds(self,
                                  mat_path: str,
                                  xml_path: str) -> Optional[List[Dict]]:
        """
        Attempt to load a snapshot with the optional ``pyMCDS`` / ``pcdl``
        package.

        Returns ``None`` when neither package is importable, signalling
        the caller to fall back to the direct parser. Any other failure
        also returns ``None`` (after a warning) so the fallback can run.

        Parameters
        ----------
        mat_path : str
            Absolute path to the ``.mat`` cells file.
        xml_path : str
            Absolute path to the matching ``.xml`` PhysiCell snapshot.

        Returns
        -------
        list of dict or None
            The list of cell dicts in the standard schema on success;
            ``None`` if pyMCDS/pcdl is unavailable or fails.
        """
        import warnings

        mcds_cls = None
        try:  # Prefer the modern pcdl entrypoint.
            from pcdl import pyMCDS as mcds_cls  # type: ignore
        except ImportError:
            try:
                from pyMCDS import pyMCDS as mcds_cls  # type: ignore
            except ImportError:
                return None

        try:
            xml_basename = os.path.basename(xml_path)
            output_dir = os.path.dirname(os.path.abspath(xml_path)) or "."
            mcds = mcds_cls(xml_basename, output_dir)
            df = mcds.get_cell_df()
        except Exception as exc:  # noqa: BLE001 - pyMCDS may raise many types
            warnings.warn(
                f"pyMCDS failed to read {mat_path!r} ({exc}); "
                "falling back to direct scipy.io parser.",
                stacklevel=3,
            )
            return None

        cells: List[Dict] = []
        # pyMCDS produces a pandas DataFrame with columns like
        # 'ID', 'position_x', 'position_y', 'position_z', 'total_volume',
        # 'cell_type'. Map them defensively.
        for _, row in df.iterrows():
            try:
                x = float(row.get("position_x", row.get("x", 0.0)))
                y = float(row.get("position_y", row.get("y", 0.0)))
                z = float(row.get("position_z", row.get("z", 0.0)))
                volume = row.get("total_volume", row.get("volume", None))
                volume = float(volume) if volume is not None else None
            except (TypeError, ValueError):
                continue

            radius = _volume_to_radius(volume) if volume is not None else self.default_radius

            raw_type = row.get("cell_type", row.get("cell_type_id", "unknown"))
            cell_type = str(raw_type).strip() or "unknown"

            cell: Dict = {
                "x": x,
                "y": y,
                "z": z,
                "radius": float(radius),
                "cell_type": cell_type,
            }
            if volume is not None:
                cell["volume"] = volume
            raw_id = row.get("ID", row.get("id", None))
            if raw_id is not None:
                cell["id"] = str(raw_id)
            cells.append(cell)

        return cells

    def _load_mat_with_scipy(self,
                             mat_path: str,
                             xml_path: Optional[str]) -> List[Dict]:
        """
        Direct ``scipy.io.loadmat`` parser implementing the documented
        PhysiCell 1.10+ default cells-matrix column layout.

        Parameters
        ----------
        mat_path : str
            Absolute path to the ``.mat`` cells file.
        xml_path : str or None
            Optional matching ``.xml`` snapshot path. When provided and
            parseable, used to remap integer ``cell_type`` IDs to string
            names from ``<cell_definitions>``.

        Returns
        -------
        list of dict
            One dict per cell in the standard schema.

        Raises
        ------
        ValueError
            If the file is not a valid MATLAB file or the cells matrix
            cannot be identified.
        """
        import warnings

        try:
            from scipy.io import loadmat  # lazy import
        except ImportError as exc:  # pragma: no cover - scipy required at runtime
            raise ImportError(
                "scipy is required to read PhysiCell .mat snapshots. "
                "Install scipy or convert the snapshot to CSV first."
            ) from exc

        try:
            data = loadmat(mat_path)
        except Exception as exc:  # noqa: BLE001
            raise ValueError(
                f"Failed to read PhysiCell .mat file {mat_path!r}: {exc}"
            ) from exc

        matrix = self._select_cells_matrix(data, mat_path)

        # The PhysiCell convention is (n_signals, n_cells). The standard
        # layout uses 6 leading signals (id, x, y, z, volume, type) — any
        # PhysiCell run emits at least these. If the second axis is the
        # larger axis we treat it as the cells axis. Otherwise we
        # transpose so that columns become cells.
        if matrix.ndim != 2:
            raise ValueError(
                f"Expected a 2-D cells matrix in {mat_path!r}, got shape "
                f"{matrix.shape}"
            )

        # PhysiCell stores cells as (n_signals, n_cells); axis 0 is signals.
        # We trust this convention rather than guessing from shape, because
        # "shorter axis is signals" mis-decodes non-standard exports such as
        # (1000, 5) or (5, 1000) where the documented column layout simply
        # cannot be satisfied. Files with rows < 6 are rejected.
        n_signals_required = 6
        rows, cols = matrix.shape
        if rows < n_signals_required:
            raise ValueError(
                f"PhysiCell cells matrix in {mat_path!r} has shape "
                f"{matrix.shape}; axis 0 (signals) has only {rows} entries "
                f"but the documented PhysiCell 1.10+ layout needs at least "
                f"{n_signals_required} (id, x, y, z, total_volume, cell_type). "
                "If the file was saved transposed, transpose it before "
                "loading or supply ``xml_path`` and rely on pyMCDS."
            )
        n_signals, n_cells = rows, cols

        def _row(signal_index: int) -> np.ndarray:
            return np.asarray(matrix[signal_index, :], dtype=float)

        ids = _row(0)
        xs = _row(1)
        ys = _row(2)
        zs = _row(3)
        volumes = _row(4)
        type_ids = _row(5)

        # Optional XML-driven cell_type-id-to-name mapping.
        type_id_to_name: Dict[int, str] = {}
        if xml_path is not None and os.path.isfile(xml_path):
            try:
                type_id_to_name = self._parse_cell_definitions_xml(xml_path)
            except Exception as exc:  # noqa: BLE001
                warnings.warn(
                    f"Failed to parse PhysiCell XML {xml_path!r} ({exc}); "
                    "cell types will be stringified integer IDs.",
                    stacklevel=2,
                )
                type_id_to_name = {}

        if not type_id_to_name:
            warnings.warn(
                "No PhysiCell cell-definition mapping available "
                "(pyMCDS unavailable and/or xml_path missing); "
                "cell_type values will be stringified integer IDs.",
                stacklevel=2,
            )

        cells: List[Dict] = []
        for i in range(n_cells):
            volume = float(volumes[i])
            radius = _volume_to_radius(volume) if volume > 0 else self.default_radius
            type_id_int = int(round(float(type_ids[i])))
            cell_type = type_id_to_name.get(type_id_int, str(type_id_int))

            cell: Dict = {
                "x": float(xs[i]),
                "y": float(ys[i]),
                "z": float(zs[i]),
                "radius": float(radius),
                "cell_type": cell_type,
            }
            if volume > 0:
                cell["volume"] = volume
            cell["id"] = str(int(round(float(ids[i]))))
            cells.append(cell)

        return cells

    @staticmethod
    def _select_cells_matrix(data: Dict, mat_path: str) -> np.ndarray:
        """
        Pick the cells matrix out of a loaded ``scipy.io.loadmat`` dict.

        The selection runs in two stages:

        1. **Named lookup.** Standard PhysiCell exports store the cells
           matrix under one of ``cells``, ``cell``, or ``Cells``. If
           exactly one of these names resolves to a 2-D ndarray, it is
           returned without further inspection and without warning.

        2. **Shape-aware heuristic.** For unusual exports that use a
           custom variable name, every 2-D numeric ndarray with a minor
           axis of at least six (the documented PhysiCell signal count)
           is scored by

           ``score = (max_axis / min_axis) * plausibility_boost``

           where ``plausibility_boost`` is ``1.5`` when the minor axis is
           in ``[6, 250]`` (a plausible PhysiCell signal count) and
           ``0.5`` otherwise. The candidate with the highest score is
           selected and a :class:`UserWarning` is emitted naming the
           chosen variable. PhysiCell cells matrices are strongly
           elongated (``n_signals`` is typically 6-200 while ``n_cells``
           can reach millions), which the elongation ratio captures.
           Microenvironment matrices share the same shape family, so the
           heuristic cannot be perfect; the warning makes mis-selection
           visible.

        Parameters
        ----------
        data : dict
            The dict returned by ``scipy.io.loadmat``.
        mat_path : str
            Source file path, used only in warnings and error messages.

        Returns
        -------
        ndarray
            The selected 2-D cells matrix.

        Raises
        ------
        ValueError
            If no 2-D numeric ndarray candidate can be found, or if the
            top two heuristic candidates score within 10% of each other
            and neither was selected via the named-lookup path.
        """
        import warnings

        preferred_names = ("cells", "cell", "Cells")
        for name in preferred_names:
            value = data.get(name)
            if isinstance(value, np.ndarray) and value.ndim == 2:
                return value

        # Collect 2-D numeric candidates with a plausible signal count.
        raw_candidates = [
            (name, value) for name, value in data.items()
            if not name.startswith("__")
            and isinstance(value, np.ndarray)
            and value.ndim == 2
            and value.size > 0
            and np.issubdtype(value.dtype, np.number)
        ]
        candidates = [
            (name, value) for name, value in raw_candidates
            if min(value.shape) >= 6
        ]
        if not candidates:
            raise ValueError(
                f"No cells matrix found in PhysiCell .mat file {mat_path!r}. "
                f"Looked for variables {preferred_names} and any 2-D numeric "
                "ndarray with both axes >= 6 (the documented PhysiCell "
                "signal count)."
            )

        def _score(arr: np.ndarray) -> float:
            shape_min = min(arr.shape)
            shape_max = max(arr.shape)
            elongation = float(shape_max) / float(shape_min)
            boost = 1.5 if 6 <= shape_min <= 250 else 0.5
            return elongation * boost

        scored = sorted(
            ((name, value, _score(value)) for name, value in candidates),
            key=lambda item: item[2],
            reverse=True,
        )
        top_name, top_value, top_score = scored[0]

        if len(scored) > 1:
            second_name, second_value, second_score = scored[1]
            if second_score > 0 and top_score / second_score < 1.1:
                raise ValueError(
                    f"Ambiguous cells matrix in {mat_path!r}: candidates "
                    f"{top_name!r} (shape {top_value.shape}) and "
                    f"{second_name!r} (shape {second_value.shape}) score "
                    "within 10% of each other under the shape-aware "
                    "heuristic. Rename the cells variable to 'cells' or "
                    "load via pyMCDS to disambiguate."
                )

        warnings.warn(
            f"PhysiCell .mat file {mat_path!r} has no standard cells "
            f"variable ({preferred_names}); falling back to shape-aware "
            f"heuristic and selecting {top_name!r} with shape "
            f"{top_value.shape}.",
            UserWarning,
            stacklevel=3,
        )
        return top_value

    @staticmethod
    def _parse_cell_definitions_xml(xml_path: str) -> Dict[int, str]:
        """
        Parse a PhysiCell snapshot XML and return an integer-ID to
        cell-type-name mapping.

        Looks for ``<cell_definitions><cell_definition ID="..." name="...">``
        nodes anywhere in the document (the exact path varies across
        PhysiCell versions, so the search is structural rather than
        positional).

        Parameters
        ----------
        xml_path : str
            Absolute path to the ``output*.xml`` file.

        Returns
        -------
        dict
            Mapping of integer cell-type ID to its string name. Empty
            when no ``<cell_definition>`` elements are present.
        """
        import xml.etree.ElementTree as ET  # lazy import

        tree = ET.parse(xml_path)
        root = tree.getroot()
        mapping: Dict[int, str] = {}
        for cd in root.iter("cell_definition"):
            raw_id = cd.attrib.get("ID")
            name = cd.attrib.get("name")
            if raw_id is None or name is None:
                continue
            try:
                type_id = int(raw_id)
            except (TypeError, ValueError):
                continue
            mapping[type_id] = str(name).strip()
        return mapping

    def load_time_series(self,
                         output_dir: str,
                         pattern: str = "snapshot_*.csv"
                         ) -> List[Tuple[float, List[Dict]]]:
        """
        Load a directory of PhysiCell snapshot CSVs as a time series.

        Parameters
        ----------
        output_dir : str
            Directory containing snapshot CSV files.
        pattern : str
            Glob pattern relative to ``output_dir`` matching snapshot files.

        Returns
        -------
        list of (float, list of dict)
            Tuples of ``(timestep, cells)`` sorted by timestep ascending.
            The timestep is extracted from the numeric token in each
            filename (e.g. ``snapshot_00010.csv`` -> 10.0).
        """
        if not os.path.isdir(output_dir):
            raise FileNotFoundError(f"Output directory not found: {output_dir}")

        matches = sorted(glob.glob(os.path.join(output_dir, pattern)))
        series: List[Tuple[float, str, List[Dict]]] = []
        for path in matches:
            timestep = _extract_timestep(path)
            cells = self.load_snapshot_csv(path)
            series.append((timestep, path, cells))

        # Sort primarily by timestep, with the filename as a stable tiebreaker
        # so collisions (e.g., files lacking digits) preserve a deterministic
        # order rather than relying on dict insertion.
        series.sort(key=lambda item: (item[0], item[1]))
        return [(ts, cells) for ts, _path, cells in series]

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------
    def compute_spatial_stats(self,
                              cells: List[Dict],
                              mode: str = "contact",
                              radius_threshold: Optional[float] = None) -> Dict:
        """
        Compute spatial statistics matching the ``tissue_simulator`` schema.

        Parameters
        ----------
        cells : list of dict
            Cell records as returned by :meth:`load_snapshot_csv`. Each
            must contain ``x``, ``y``, ``z``, ``radius``, and ``cell_type``.
        mode : str
            ``"contact"`` to connect cells whose surfaces touch
            (``distance <= r_i + r_j`` with a 1% tolerance matching
            ``SpatialNetworkAnalyzer``) or ``"radius"`` to connect cells
            within ``radius_threshold`` of each other (center to center).
        radius_threshold : float, optional
            Distance threshold for ``radius`` mode. Required when
            ``mode == "radius"``.

        Returns
        -------
        dict
            Dictionary with keys ``node_counts``, ``edge_counts``, and
            ``neighbor_dist``.

            - ``node_counts`` : ``Dict[str, int]`` mapping cell type to
              cell count.
            - ``edge_counts`` : ``Dict[str, int]`` mapping a sorted
              ``"type_a-type_b"`` key to the number of contacts.
            - ``neighbor_dist`` : ``Dict[str, Dict[str, float]]`` mapping
              ``type_a`` to a dict of ``type_b`` to the average number of
              ``type_b`` neighbors for a ``type_a`` cell.
        """
        if mode not in {"contact", "radius"}:
            raise ValueError(f"mode must be 'contact' or 'radius', got {mode!r}")
        if mode == "radius" and (radius_threshold is None or radius_threshold <= 0):
            raise ValueError("radius_threshold must be a positive float for 'radius' mode")
        if not SCIPY_AVAILABLE:
            raise ImportError(
                "scipy is required for spatial statistics. "
                "Install with: pip install scipy"
            )

        node_counts: Dict[str, int] = defaultdict(int)
        edge_counts: Dict[str, int] = defaultdict(int)
        neighbor_counts: Dict[str, Dict[str, int]] = defaultdict(
            lambda: defaultdict(int)
        )

        for cell in cells:
            node_counts[cell["cell_type"]] += 1

        if len(cells) < 2:
            return {
                "node_counts": dict(node_counts),
                "edge_counts": {},
                "neighbor_dist": {},
            }

        positions = np.array(
            [(c["x"], c["y"], c.get("z", 0.0)) for c in cells], dtype=float
        )
        radii = np.array([float(c["radius"]) for c in cells], dtype=float)
        types = [c["cell_type"] for c in cells]

        tree = KDTree(positions)

        if mode == "contact":
            # Tolerance matches SpatialNetworkAnalyzer (1%).
            tolerance = 1.01
            search_radius = float(radii.max()) * 2.0 * tolerance
            neighbor_lists = tree.query_ball_point(positions, r=search_radius)
            seen = set()
            for i, neighbors in enumerate(neighbor_lists):
                for j in neighbors:
                    if j <= i:
                        continue
                    distance = float(np.linalg.norm(positions[i] - positions[j]))
                    if distance <= (radii[i] + radii[j]) * tolerance:
                        seen.add((i, j))
            edge_iter = seen
        else:
            pairs = tree.query_pairs(r=float(radius_threshold))
            edge_iter = pairs

        for i, j in edge_iter:
            t_i, t_j = types[i], types[j]
            key = "-".join(sorted([t_i, t_j]))
            edge_counts[key] += 1
            neighbor_counts[t_i][t_j] += 1
            if t_i != t_j:
                neighbor_counts[t_j][t_i] += 1
            else:
                # Both endpoints share the same type; count each direction once
                # more so the average neighbor counts reflect both endpoints.
                neighbor_counts[t_i][t_j] += 1

        neighbor_dist: Dict[str, Dict[str, float]] = {}
        for t_a, t_a_count in node_counts.items():
            if t_a_count <= 0:
                continue
            neighbor_dist[t_a] = {}
            for t_b in node_counts:
                neighbor_dist[t_a][t_b] = (
                    neighbor_counts[t_a].get(t_b, 0) / t_a_count
                )

        return {
            "node_counts": dict(node_counts),
            "edge_counts": dict(edge_counts),
            "neighbor_dist": neighbor_dist,
        }

    def compute_stats_time_series(self,
                                  time_series: List[Tuple[float, List[Dict]]],
                                  mode: str = "contact",
                                  radius_threshold: Optional[float] = None
                                  ) -> List[Tuple[float, Dict]]:
        """
        Apply :meth:`compute_spatial_stats` over a time series.

        Parameters
        ----------
        time_series : list of (float, list of dict)
            Output of :meth:`load_time_series`.
        mode : str
            See :meth:`compute_spatial_stats`.
        radius_threshold : float, optional
            See :meth:`compute_spatial_stats`.

        Returns
        -------
        list of (float, dict)
            Tuples of ``(timestep, stats)`` where ``stats`` is the dict
            returned by :meth:`compute_spatial_stats`.
        """
        results: List[Tuple[float, Dict]] = []
        for timestep, cells in time_series:
            stats = self.compute_spatial_stats(
                cells, mode=mode, radius_threshold=radius_threshold
            )
            results.append((float(timestep), stats))
        return results


def read_physicell_output(path: str, **kwargs
                          ) -> Union[List[Dict], List[Tuple[float, List[Dict]]]]:
    """
    Read PhysiCell output from a file or directory.

    Convenience entry point that dispatches based on ``path``:

    - If ``path`` is a directory, returns a time series via
      :meth:`PhysiCellReader.load_time_series`.
    - If ``path`` ends in ``.csv``, returns a single snapshot list via
      :meth:`PhysiCellReader.load_snapshot_csv`.
    - If ``path`` ends in ``.mat``, dispatches to
      :meth:`PhysiCellReader.load_snapshot_mat`.

    Parameters
    ----------
    path : str
        Path to a snapshot file or an output directory.
    **kwargs
        Forwarded to the dispatched loader (e.g. ``pattern`` for
        directories, ``xml_path`` for ``.mat`` files,
        ``default_radius`` for the reader itself).

    Returns
    -------
    list
        Either a list of cell dicts (single snapshot) or a list of
        ``(timestep, cells)`` tuples (directory).
    """
    default_radius = kwargs.pop("default_radius", _DEFAULT_RADIUS)
    reader = PhysiCellReader(default_radius=default_radius)

    if os.path.isdir(path):
        pattern = kwargs.pop("pattern", "snapshot_*.csv")
        if kwargs:
            raise TypeError(f"Unexpected keyword arguments: {sorted(kwargs)}")
        return reader.load_time_series(path, pattern=pattern)

    lower = path.lower()
    if lower.endswith(".mat"):
        xml_path = kwargs.pop("xml_path", None)
        if kwargs:
            raise TypeError(f"Unexpected keyword arguments: {sorted(kwargs)}")
        return reader.load_snapshot_mat(path, xml_path=xml_path)

    if lower.endswith(".csv"):
        if kwargs:
            raise TypeError(f"Unexpected keyword arguments: {sorted(kwargs)}")
        return reader.load_snapshot_csv(path)

    raise ValueError(
        f"Unsupported PhysiCell output path: {path!r}. Expected a "
        "directory or a .csv/.mat file."
    )


def stats_to_target_statistics(stats: Dict,
                               target_cell_count: Optional[int] = None,
                               target_density: Optional[float] = None):
    """
    Convert a reader stats dict to a :class:`TargetStatistics` dataclass.

    The dict returned by :meth:`PhysiCellReader.compute_spatial_stats` uses
    the schema accepted internally by :class:`GraphColorizer`. The
    :class:`~tissue_simulator.replicate_generator.ReplicateGenerator` expects
    a different shape: a list of
    :class:`~tissue_simulator.spatial_analysis.InteractionStatistics` plus
    cell-type proportions. This adapter performs that conversion.

    Average and median distances are not present in the reader's output and
    are set to ``0.0`` on the synthesized interaction records; callers that
    need real distance statistics should compute them separately.

    Parameters
    ----------
    stats : dict
        Output of :meth:`PhysiCellReader.compute_spatial_stats`. Must
        contain ``node_counts``, ``edge_counts`` and ``neighbor_dist``.
    target_cell_count : int, optional
        Optional total cell count to attach to the resulting
        ``TargetStatistics`` instance. When omitted, the sum of
        ``node_counts`` is used.
    target_density : float, optional
        Optional target packing fraction to attach.

    Returns
    -------
    TargetStatistics
        The converted dataclass, ready to pass to
        :class:`~tissue_simulator.replicate_generator.ReplicateGenerator`.
    """
    # Local imports avoid a circular dependency at module load time.
    from .replicate_generator import TargetStatistics
    from .spatial_analysis import InteractionStatistics

    node_counts = dict(stats.get("node_counts") or {})
    edge_counts = dict(stats.get("edge_counts") or {})
    total_cells = sum(node_counts.values())

    cell_type_proportions: Dict[str, float] = {}
    if total_cells > 0:
        cell_type_proportions = {
            t: count / total_cells for t, count in node_counts.items()
        }

    interaction_stats: List = []
    seen_pairs = set()
    cell_types = sorted(node_counts.keys())
    for i, type_a in enumerate(cell_types):
        for type_b in cell_types[i:]:
            key = "-".join(sorted([type_a, type_b]))
            if key in seen_pairs:
                continue
            seen_pairs.add(key)
            num = int(edge_counts.get(key, 0))
            n_a = node_counts.get(type_a, 0)
            n_b = node_counts.get(type_b, 0)
            denom = (n_a * n_b) if type_a != type_b else (n_a * (n_a - 1) / 2)
            normalized = float(num) / float(denom) if denom > 0 else 0.0
            interaction_stats.append(
                InteractionStatistics(
                    type_a=type_a,
                    type_b=type_b,
                    num_interactions=num,
                    normalized_interactions=normalized,
                    avg_distance=0.0,
                    median_distance=0.0,
                )
            )

    resolved_count = (
        int(target_cell_count) if target_cell_count is not None
        else int(total_cells) if total_cells > 0 else None
    )
    return TargetStatistics(
        interaction_stats=interaction_stats,
        cell_type_proportions=cell_type_proportions or None,
        target_cell_count=resolved_count,
        target_density=target_density,
    )
